[project]
name = 'Transparent-Pharmaceutical-Supply-Chain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.drug-registration]
path = 'contracts/drug-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-control]
path = 'contracts/quality-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.recall-management]
path = 'contracts/recall-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
